name: extensions
description: Reusable extensions
version: 0.7.0
homepage: https://twitter.com/hikeland
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  
  localization: ^2.1.0

  riverpod_annotation: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  riverpod_generator: ^2.2.4

flutter:

dependency_overrides:
  intl: any